### PR TITLE
[#1826] fix(test): Fix flakiness in AMQ4930Test

### LINKED ISSUE #1826: Flaky test in queue browse memory regression test (AMQ4930Test)
The regression test added for AMQ-4930 relies on JVM heap memory assertions using Runtime.freeMemory(), which makes the test inherently flaky and non-deterministic across environments.

```
Error:  Failures: 
Error:    AMQ4930Test.testBrowsePendingPersistent:70->doTestBrowsePending:123 No growth: 72509 >= 72760.0
Error:    AMQ4930Test.testWithStatsDisabled:75->doTestBrowsePending:123 No growth: 72128 >= 71421.6
```

### PR DESCRIPTION
**Pull request by gurpartap3697**
fixes #1826 
This PR addresses the flakiness in AMQ4930Test.

Existing test relies on Runtime.freeMemory() and explicit gc() calls, which makes the test flaky due to JVM heap resizing and GC timing variability.

### CODE REVIEW

File: activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java [hunk 1]
```diff
@@ -110,17 +110,15 @@ public void doTestBrowsePending(int deliveryMode) throws Exception {
...
         // check for memory growth
         for (int i=0; i<10; i++) {
             LOG.info("free: " + Runtime.getRuntime().freeMemory()/1024);
             browsed = underTest.browse();
             LOG.info("Browsed: " + browsed.length);
             assertEquals("maxBrowsePageSize", maxBrowsePageSize, browsed.length);
-            Runtime.getRuntime().gc();
-            Runtime.getRuntime().gc();
-            assertTrue("No growth: " + Runtime.getRuntime().freeMemory()/1024 + " >= " + (free - (free * 0.2)), Runtime.getRuntime().freeMemory()/1024 >= (free - (free * 0.2)));
+            assertTrue("Memory usage is ballooning: " + underTest.getMemoryUsage().getUsage() + " > " + memoryUsageAtStart, underTest.getMemoryUsage().getUsage() <= memoryUsageAtStart);
```
Comment (jbonofre) [inline activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java]: I think it's a bit strict here.

Currently the test has 20% tolerance.

Your overall approach is better: the broker memory accounting is more deterministic than JVM free memory.
However, we can observe minor transient fluctuations.

I suggest to keep a tolerance margin here to avoid flakiness still:


```suggestion
            assertTrue("Memory usage is ballooning: " + underTest.getMemoryUsage().getUsage() + " > " + memoryUsageAtStart, underTest.getMemoryUsage().getUsage() <= memoryUsageAtStart * 1.1);
```

File: activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java [hunk 2]
```diff
@@ -110,17 +110,15 @@ public void doTestBrowsePending(int deliveryMode) throws Exception {
         LOG.info("Browsed: " + browsed.length);
         assertEquals("maxBrowsePageSize", maxBrowsePageSize, browsed.length);
         Runtime.getRuntime().gc();
```
Comment (jbonofre) [inline activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java]: As we are not using JVM free memory anymore, we can remove this `gc()` call.

File: activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java [hunk 3]
```diff
@@ -110,17 +110,15 @@ public void doTestBrowsePending(int deliveryMode) throws Exception {
...
-        long free = Runtime.getRuntime().freeMemory()/1024;
-        LOG.info("free at start of check: " + free);
+        long memoryUsageAtStart = underTest.getMemoryUsage().getUsage();
+        LOG.info("Memory usage at start of check: " + memoryUsageAtStart);
         // check for memory growth
         for (int i=0; i<10; i++) {
             LOG.info("free: " + Runtime.getRuntime().freeMemory()/1024);
```
Comment (jbonofre) [inline activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java]: Same here: as we are not using JVM free memory anymore, we can remove this log message.

File: activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java (hunk 1 above)
Comment (gurpartap3697) [reply activemq-unit-tests/src/test/java/org/apache/activemq/bugs/AMQ4930Test.java]: Agree, will update

**Comment by gurpartap3697** [comment]
Thanks for the feedback — updated the pr with suggested changes.

**Comment by jbonofre** [comment]
@gurpartap3697 I will merge as soon as CI is happy.
